# Generated by Django 3.1.5 on 2021-02-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210210_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='post',
            name='psa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='repost',
        ),
        migrations.AddField(
            model_name='article',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psa',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repost',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
