# Generated by Django 3.1.5 on 2021-02-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210210_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('psa', 'PSA'), ('poll', 'Poll'), ('meme', 'Meme'), ('repost', 'Repost'), ('article', 'Article')], default='psa', max_length=10),
            preserve_default=False,
        ),
    ]
