# Generated by Django 3.1.5 on 2021-02-12 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
