# Generated by Django 3.1.5 on 2021-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210212_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
