# Generated by Django 3.1.5 on 2021-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210212_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video_type',
            field=models.CharField(choices=[('vimeo', 'Vimeo'), ('youtube', 'Youtube')], default='vimeo', max_length=10),
            preserve_default=False,
        ),
    ]
