# Generated by Django 3.1.5 on 2021-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210212_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
