# Generated by Django 3.1.5 on 2021-02-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='category',
        ),
        migrations.RemoveField(
            model_name='psa',
            name='category',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='category',
        ),
    ]
