# Generated by Django 3.1.5 on 2021-03-01 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_poll_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes',
            new_name='upvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
        migrations.AddField(
            model_name='post',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(related_name='voted_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
