# Generated by Django 3.1.5 on 2021-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20210303_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
