# Generated by Django 3.1.5 on 2021-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, null=True, blank=True),
        ),
    ]
