# Generated by Django 3.1.5 on 2021-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phoneverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneverification',
            old_name='created',
            new_name='created_at',
        ),
    ]
