# Generated by Django 3.1.5 on 2021-01-13 01:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210112_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='avatar'),
        ),
    ]
