# Generated by Django 3.1.5 on 2021-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210118_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accuracy',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='contribution',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ethics',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fairness',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of posts'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0, editable=False, verbose_name='Average rating'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of subscribers'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
