# Generated by Django 3.1.5 on 2021-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accuracy',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='contribution',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethics',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='expertise',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='fairness',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
