# Generated by Django 3.1.5 on 2021-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210121_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of comments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reviews',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reviews'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of subscribers'),
        ),
    ]
