# Generated by Django 3.1.5 on 2021-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210122_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='own_reviews',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of personal reviews'),
        ),
    ]
