# Generated by Django 3.1.5 on 2021-03-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210306_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
    ]
