# Generated by Django 3.1.5 on 2021-01-22 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='agreed',
            field=models.ManyToManyField(related_name='agreed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='disagreed',
            field=models.ManyToManyField(related_name='disagreed', to=settings.AUTH_USER_MODEL),
        ),
    ]
