# Generated by Django 3.1.5 on 2021-01-22 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20210122_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='agreed',
            field=models.ManyToManyField(blank=True, related_name='agreed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='disagreed',
            field=models.ManyToManyField(blank=True, related_name='disagreed', to=settings.AUTH_USER_MODEL),
        ),
    ]
