# Generated by Django 3.1.5 on 2021-01-29 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_auto_20210129_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='agreed',
            field=models.ManyToManyField(blank=True, related_name='response_agreed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='disagreed',
            field=models.ManyToManyField(blank=True, related_name='response_disagreed', to=settings.AUTH_USER_MODEL),
        ),
    ]
